### ISSUE TITLE
Custom Font not working

### ISSUE THREAD

**Issue by fateenarinah** [dompdf/php-svg-lib#123]
Hi! I'm encountering an issue with an SVG image that uses the Open Sans font family. When I upload it into Dompdf, the font family gets changed to something else. I've already tried setting the SVG code to use the Open Sans font family, but it's not working. I'd greatly appreciate it if someone could guide me on how to properly utilize the Open Sans font family in my SVG code. 

Below is the SVG code I'm currently using.

![Screenshot 2024-07-05 121805](https://github.com/dompdf/php-svg-lib/assets/31203974/4e003fac-bf59-4558-9371-c3278c5d5954)

and the output
![Screenshot 2024-07-05 121934](https://github.com/dompdf/php-svg-lib/assets/31203974/ad440c43-d9d3-4c5d-abfe-9f6fce079039)

I've examined the SVG code using the SVG Viewer and have attached the output below. It appears to be functioning properly there, but when I transfer it to Dompdf, an issue similar to the one shown in the first screenshot arises.

![Screenshot 2024-07-05 121958](https://github.com/dompdf/php-svg-lib/assets/31203974/5ed6aff4-e5dc-4e2a-854b-a98b38749a14)

**Comment by bsweeney** [comment]
SvgLib does not yet have font management logic. Because of this you have to specify the path to the font file instead of the font name, unless you're using a core PDF font such as helvetica or a generic font family such as sans-serif. Follow #110 for updates.

I see you also have a tspan in there, which is also not yet supported. Follow #64 for updates on that feature.
