### ISSUE TITLE
Division by zero in arcToSegments function

### ISSUE THREAD

**Issue by ljadrbln** [dompdf/php-svg-lib#97]
Hello,

I have «Division by zero» error with next svg file:
![rabbit](https://user-images.githubusercontent.com/647352/202432423-d42ce44e-ac0f-4cf5-8d86-c65c3dc0c978.svg)
```
[C:/App/vendor/phenx/php-svg-lib/src/Svg/Tag/Path.php:504] Base->{closure}()
[C:/App/vendor/phenx/php-svg-lib/src/Svg/Tag/Path.php:457] Svg\Tag\Path->arcToSegments()
[C:/App/vendor/phenx/php-svg-lib/src/Svg/Tag/Path.php:395] Svg\Tag\Path->drawArc()
[C:/App/vendor/phenx/php-svg-lib/src/Svg/Tag/AbstractTag.php:64] Svg\Tag\Path->start()
[C:/App/vendor/phenx/php-svg-lib/src/Svg/Document.php:357] Svg\Tag\AbstractTag->handle()
[C:/App/vendor/phenx/php-svg-lib/src/Svg/Document.php:225] xml_parse()
[C:/App/vendor/dompdf/dompdf/lib/Cpdf.php:5910] Svg\Document->render()
[C:/App/vendor/dompdf/dompdf/src/Adapter/CPDF.php:675] Dompdf\Cpdf->addSvgFromFile()
[C:/App/vendor/dompdf/dompdf/src/Renderer/Image.php:65] Dompdf\Adapter\CPDF->image()
[C:/App/vendor/dompdf/dompdf/src/Renderer.php:289] Dompdf\Renderer\Image->render()
[C:/App/vendor/dompdf/dompdf/src/Renderer.php:128] Dompdf\Renderer->_render_frame()
[C:/App/vendor/dompdf/dompdf/src/Renderer.php:195] Dompdf\Renderer->render()
[C:/App/vendor/dompdf/dompdf/src/Renderer.php:195] Dompdf\Renderer->render()
[C:/App/vendor/dompdf/dompdf/src/Renderer.php:195] Dompdf\Renderer->render()
[C:/App/vendor/dompdf/dompdf/src/FrameReflower/Page.php:149] Dompdf\Renderer->render()
[C:/App/vendor/dompdf/dompdf/src/Dompdf.php:765] Dompdf\FrameDecorator\AbstractFrameDecorator->reflow()
```

The rough workaround is to modify **arcToSegments** function in the **Svg\Surface\SurfaceInterface\Path**:
```
$ry = $ry ? $ry : 0.1;
$py = $py ? $py : 0.1;
$rx = $rx ? $rx : 0.1;
$px = $px ? $px : 0.1;
```
But maybe more elegant solution exists?

**Comment by bsweeney** [comment]
The issue appears to be caused by a path command defining an arc where one or both of the radii are zero. You can reproduce the error with the following simple example:

```
<svg id="svg" xmlns="http://www.w3.org/2000/svg" width="200" height="200">
  <path d="M 25 25 a 5 0 5 0 0 50 50" stroke="orange" stroke-width="5" fill="none"/>
</svg>
```

<img width="53" alt="image" src="https://github.com/dompdf/php-svg-lib/assets/485897/fe7f5b50-a2ae-47d9-8d0a-e73f343fa5cd">

Without a radius the arc is actually just a line. That makes for a simple solution to the issue, render a line instead of an arc.

---

Note that I would definitely not recommend using the suggested workaround. Changing a radius from 0 to .1 can have a significant impact on the rendering, as you can see when the radius in the above sample is changed.

```
<svg id="svg" xmlns="http://www.w3.org/2000/svg" width="200" height="200">
  <path d="M 25 25 a 5 .1 5 0 0 50 50" stroke="orange" stroke-width="5" fill="none"/>
</svg>
```

<img width="59" alt="image" src="https://github.com/dompdf/php-svg-lib/assets/485897/986d31ee-4c52-46ef-b833-f55be92f8f04">
